### ISSUE TITLE
book:0.10.0rc2-gpu镜像以--gpu_use=1方式运行示例报错

### ISSUE THREAD

**Issue by llxxxll** [PaddlePaddle/book#272]
docker 镜像run命令
`docker run -it docker.paddlepaddle.org/book:0.10.0rc2-gpu /bin/bash`
修改
`03.image_classification/train.py`
28行
`paddle.init(use_gpu=False, trainer_count=1)`
为
`paddle.init(use_gpu=1, trainer_count=1)`
运行
`python train.py`
错误信息如下：

> I0406 14:21:50.500150   150 Util.cpp:161] commandline:  --use_gpu=1 --trainer_count=1 
F0406 14:21:50.500263   150 hl_cuda_device.cc:454] Check failed: cudaSuccess == cudaStat (0 vs. 35) Cuda Error: CUDA driver version is insufficient for CUDA runtime version
*** Check failure stack trace: ***
    @     0x7fbeb915137d  google::LogMessage::Fail()
    @     0x7fbeb9154ec5  google::LogMessage::SendToLog()
    @     0x7fbeb9150ea3  google::LogMessage::Flush()
    @     0x7fbeb91563de  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fbeb910e5fe  hl_specify_devices_start()
    @     0x7fbeb910e8ed  hl_start()
    @     0x7fbeb90996ea  paddle::initMain()
    @     0x7fbeb91380a0  initPaddle()
    @     0x7fbeb8d71d6a  _wrap_initPaddle
    @           0x52714b  PyEval_EvalFrameEx
    @           0x555551  PyEval_EvalCodeEx
    @           0x525560  PyEval_EvalFrameEx
    @           0x568b3a  (unknown)
    @           0x525cb7  PyEval_EvalFrameEx
    @           0x555551  PyEval_EvalCodeEx
    @           0x525560  PyEval_EvalFrameEx
    @           0x555551  PyEval_EvalCodeEx
    @           0x525560  PyEval_EvalFrameEx
    @           0x567d14  (unknown)
    @           0x465bf4  PyRun_FileExFlags
    @           0x46612d  PyRun_SimpleFileExFlags
    @           0x466d92  Py_Main
    @     0x7fbebbf24f45  __libc_start_main
    @           0x577c2e  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

nvidia-smi信息如下：

> Thu Apr  6 22:33:01 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.51                 Driver Version: 375.51                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    Off  | 0000:01:00.0      On |                  N/A |
|  0%   44C    P5    14W / 180W |    560MiB /  8113MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
>+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1147    G   /usr/lib/xorg/Xorg                             377MiB |
|    0      2117    G   compiz                                         169MiB |
|    0      2263    G   /usr/lib/firefox/firefox                         1MiB |
|    0      2423    G   fcitx-qimpanel                                   9MiB |
+-----------------------------------------------------------------------------+

**Comment by gangliao** [comment]
@llxxxll  @Yancey1989   我文档里面已经写过了，请用nvidia-docker

**Comment by llxxxll** [comment]
@gangliao 
按照指引，已经搞定了，感谢。

**Comment by HardSoft2023** [comment]
@gangliao 使用   paddle.init(use_gpu=False, trainer_count=3)为什么会报这个错误呢？    
![image](https://user-images.githubusercontent.com/10841581/39923671-3dadf15a-5557-11e8-8c45-b02362467496.png)
